# flake8: noqa
# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema.proto',
  package='proto_scheme',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cschema.proto\x12\x0cproto_scheme\"A\n\x06Person\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x03(\t\"\xb0\x01\n\x0eGovernmentInfo\x12O\n\x13social_id_to_person\x18\x04 \x03(\x0b\x32\x32.proto_scheme.GovernmentInfo.SocialIdToPersonEntry\x1aM\n\x15SocialIdToPersonEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.proto_scheme.Person:\x02\x38\x01\x62\x06proto3'
)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='proto_scheme.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='proto_scheme.Person.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='proto_scheme.Person.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='proto_scheme.Person.language', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=95,
)


_GOVERNMENTINFO_SOCIALIDTOPERSONENTRY = _descriptor.Descriptor(
  name='SocialIdToPersonEntry',
  full_name='proto_scheme.GovernmentInfo.SocialIdToPersonEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto_scheme.GovernmentInfo.SocialIdToPersonEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto_scheme.GovernmentInfo.SocialIdToPersonEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=274,
)

_GOVERNMENTINFO = _descriptor.Descriptor(
  name='GovernmentInfo',
  full_name='proto_scheme.GovernmentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='social_id_to_person', full_name='proto_scheme.GovernmentInfo.social_id_to_person', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GOVERNMENTINFO_SOCIALIDTOPERSONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=274,
)

_GOVERNMENTINFO_SOCIALIDTOPERSONENTRY.fields_by_name['value'].message_type = _PERSON
_GOVERNMENTINFO_SOCIALIDTOPERSONENTRY.containing_type = _GOVERNMENTINFO
_GOVERNMENTINFO.fields_by_name['social_id_to_person'].message_type = _GOVERNMENTINFO_SOCIALIDTOPERSONENTRY
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['GovernmentInfo'] = _GOVERNMENTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:proto_scheme.Person)
  })
_sym_db.RegisterMessage(Person)

GovernmentInfo = _reflection.GeneratedProtocolMessageType('GovernmentInfo', (_message.Message,), {

  'SocialIdToPersonEntry' : _reflection.GeneratedProtocolMessageType('SocialIdToPersonEntry', (_message.Message,), {
    'DESCRIPTOR' : _GOVERNMENTINFO_SOCIALIDTOPERSONENTRY,
    '__module__' : 'schema_pb2'
    # @@protoc_insertion_point(class_scope:proto_scheme.GovernmentInfo.SocialIdToPersonEntry)
    })
  ,
  'DESCRIPTOR' : _GOVERNMENTINFO,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:proto_scheme.GovernmentInfo)
  })
_sym_db.RegisterMessage(GovernmentInfo)
_sym_db.RegisterMessage(GovernmentInfo.SocialIdToPersonEntry)


_GOVERNMENTINFO_SOCIALIDTOPERSONENTRY._options = None
# @@protoc_insertion_point(module_scope)
